### ISSUE TITLE
Sprite bug or software bug.

### ISSUE THREAD

**Issue by HUNK1** [HypatiaStation/HypatiaStationDev#56]
![](http://i.imgur.com/q2rI4ky.png)

![](http://i.imgur.com/8Wx9H5B.png)

Well those images explain more than i could with words.

**Comment by HUNK1** [comment]
I do not know exacly what causes it.

**Comment by Ltmayday** [comment]
Related to what i said here #34

**Comment by Fox-McCloud** [comment]
Not related. This is because you have hardware acceleration turned off or your have an incredibly old/outdated graphics card.

Go into BYOND, click the gear in the top right, then preferences...finally games tab. Ensure hardware acceleration is turned on.

Also make sure your graphics drivers are up to date.

If you've done both of those and still get this, well...unfortunately you're out of luck and won't be able to play =/
